# Brewfile
# -----------------------------------------------------------------------------

# tap
# -----------------------------------------------------------------------------
tap "coursier/formulas"
tap "homebrew/bundle"
tap "homebrew/services"

#
# -----------------------------------------------------------------------------
brew "asdf"
brew "freetype"
brew "ghq"
brew "peco"
brew "pt"                                   # the platinum searcher
brew "sheldon"
brew "tig"
brew "vim"
brew "wget"
brew "xh"
brew "zsh"
cask "font-jetbrains-mono"

# yabai + skhd (tiling window manager)
# -----------------------------------------------------------------------------
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"
