# -----------------------------------------------------------------------------
# Brewfile
# -----------------------------------------------------------------------------

# tap
# -----------------------------------------------------------------------------
tap 'homebrew/cask'
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
tap 'homebrew/bundle'
# for QMKFirmware
tap 'osx-cross/avr'
tap 'PX4/homebrew-px4'
tap 'coursier/formulas'

# cask
# -----------------------------------------------------------------------------
cask 'alfred'
cask 'appcleaner'
cask 'dropbox'
cask 'evernote'
cask 'firefox'
cask 'google-chrome'
cask 'osxfuse'
cask 'xquartz'
cask 'slack'
cask 'the-unarchiver'
cask 'skype'
cask 'vlc'
cask 'android-studio'
cask 'visual-studio-code'
cask 'arduino'

# others
# -----------------------------------------------------------------------------
brew 'awscli'
brew 'cdrtools'
brew 'coreutils'
brew 'ctags'
brew 'freetype'
brew 'gdbm'
brew 'gettext'
brew 'git'
brew 'glib'
brew 'anyenv'
brew 'jq'
brew 'mecab'
brew 'mecab-ipadic'
brew 'openssl'
brew 'p7zip'
brew 'fzf'
brew 'ripgrep'
brew 'pkg-config'
brew 'protobuf'
#brew 'python'
#brew 'python3'
brew 'readline'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'sshfs'
brew 'the_platinum_searcher'
brew 'wget'
brew 'zlib'
brew 'zsh' 
brew 'zplug'
brew 'vim'
#brew 'mysql@5.7'
#brew 'memcached'
brew 'tig'
# scala
brew 'coursier/formulas/coursier'

# for QMKFirmware
brew 'avr-gcc@8'
brew 'dfu-programmer'
brew 'dfu-util'
brew 'gcc-arm-none-eabi'
brew 'avrdude'

brew 'exa'
brew 'bat'
brew 'fd'
brew 'ripgrep'
