#!/usr/bin/env bash

DOTPATH=~/dotfiles
DOTFILES_GITHUB="https://github.com/nnno/dotfiles.git"

has() {
    which "$1" >/dev/null 2>&1
    return $?
}

if has "git"; then
    git clone --recursive "$DOTFILES_GITHUB" "$DOTPATH"
else
    die "git required."
fi

cd "$DOTPATH"
if [ $? -ne 0 ]; then
    die "not found: $DOTPATH"
fi

make install


